apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gobongbap
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
images:
- name: sce06147/gobongbap
  newTag: 11a4798e69b90ded543f2176c940c1560d383633
